# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lode < Formula
  desc ""
  homepage "https://github.com/JamesBalazs/homebrew-tools"
  version "0.5.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.5/lode_0.5.5_Darwin_x86_64.tar.gz"
      sha256 "06d2d36ce09a711792ec9de9868ceeb85a55a62e8573b594d0cc6572cbb1c7e4"

      def install
        bin.install "lode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.5/lode_0.5.5_Darwin_arm64.tar.gz"
      sha256 "0dc77747ea2f5efac94337cce0b0a43e91af2104cc9f2a3baa04600103d8e9e3"

      def install
        bin.install "lode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.5/lode_0.5.5_Linux_x86_64.tar.gz"
      sha256 "92c1984972cfa0e6c9194c12e02dc14acfe6581d96e3c410d749baab8fdbcd03"

      def install
        bin.install "lode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.5/lode_0.5.5_Linux_arm64.tar.gz"
      sha256 "cf7b8b4081ddf188329456ba0fa361e78d2cf1dd18c7255fc10f2761ca1cf900"

      def install
        bin.install "lode"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.5/lode_0.5.5_Linux_armv6.tar.gz"
      sha256 "14db2f72d91e765ee7f4e11d8c93c035765f217f8c9fb1ba659e79247846b567"

      def install
        bin.install "lode"
      end
    end
  end
end
