# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lode < Formula
  desc ""
  homepage "https://github.com/JamesBalazs/homebrew-tools"
  version "0.5.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.3/lode_0.5.3_Darwin_x86_64.tar.gz"
      sha256 "2f51754d19b81cb63633a948822d4bb5e921f6a2c28bc0b15164eda0ed2eb878"

      def install
        bin.install "lode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.3/lode_0.5.3_Darwin_arm64.tar.gz"
      sha256 "ab351c195facdce6c0c3a81546709371ef2d569b20c8fb1945f69d852f625b49"

      def install
        bin.install "lode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.3/lode_0.5.3_Linux_armv6.tar.gz"
      sha256 "eeb904657a8d4a45bda8ca4c7dd5d24bede4801c7388cd98a7809784e414da1b"

      def install
        bin.install "lode"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.3/lode_0.5.3_Linux_x86_64.tar.gz"
      sha256 "c578665e7e184d853a0a50f2137fc50e22bce217a722177adbbc61aa93123889"

      def install
        bin.install "lode"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JamesBalazs/lode/releases/download/v0.5.3/lode_0.5.3_Linux_arm64.tar.gz"
      sha256 "805c114efc67cd3b891908f920f4896375d8dc86ad884413805cc71ab8ef0cf6"

      def install
        bin.install "lode"
      end
    end
  end
end
